apiVersion: v1
kind: Pod
metadata:
  name: libvirt
  labels:
    app: libvirt
spec:
  hostNetwork: true
  containers:
    - name: daemon
      image: docker.io/fabiand/libvirtd:latest
      ports:
      - containerPort: 1923
        name: spice
      - containerPort: 5900
        name: vnc
      - containerPort: 16509
        name: libvirt
      securityContext:
        privileged: true
      command: ["libvirtd", "--listen", "--verbose"]
    - name: controller
      image: docker.io/fabiand/libvirt-client:latest
      volumeMounts:
      - name: dev
        mountPath: /dev
      - name: sys
        mountPath: /sys
      - name: etcsysconfignetworkscripts
        mountPath: /etc/sysconfig/network-scripts
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: sys
    hostPath:
      path: /sys
  - name: proc
    hostPath:
      path: /proc
  - name: etcsysconfignetworkscripts
    hostPath:
      path: /etc/sysconfig/network-scripts
